#if !canImport(ObjectiveC)
import XCTest

extension WrapperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WrapperTests = [
        ("testFailableInitDefaultImplementationFailsOnError", testFailableInitDefaultImplementationFailsOnError),
        ("testFailableInitHasDefaultImplementation", testFailableInitHasDefaultImplementation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(WrapperTests.__allTests__WrapperTests),
    ]
}
#endif
